config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#landing_page'

  post "/" => 'pages#save_email'

  get "contact" => "pages#contact"
  post "contact" => "pages#contact_mail"

  get "cgu" => "pages#cgu"

  mount Attachinary::Engine => "/attachinary"

  resources :experiences do
    post "send_experience" => "experiences#send_experience", as: 'send'
    resources :ratings, only: [:create]
    resources :wishlists, only: [:create]
  end

  post "gps_coordinates" => "images#get_gps"

  resources :roadmaps do
    get "send_roadmap" => "roadmaps#send_roadmap", as: 'send'
    resources :experiences do
      resources :activities, only: [:create]
    end
  end

  resources :roadmaps
  resources :activities, only: [:update, :destroy] do
    post "up" => "activities#up"
    post "down" => "activities#down"
  end

  get "my_experiences" => "experiences#my_experiences"

  resources :wishlists, only: [:index, :destroy]
  resources :ratings, only: [:destroy]
 end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
  belongs_to :user
  has_many :activities, dependent: :destroy
  has_many :experiences, through: :activities

  validates :user, presence: true

  validate :start_date_is_a_date_or_nil
  validate :end_date_is_a_date_or_nil
  validate :start_date_is_valid
  validate :end_date_is_valid

  after_save :cache_start_components, if: :start_destination_changed?
  after_save :cache_end_components, if: :end_destination_changed?

  default_scope { order(created_at: :desc) }

  def planning
    case self.details[:kind]
    when :city
      function = :address
    when :country
      function = :city
    else
      function = :city
    end

    start_ = send("start_#{function}")
    end_ = send("end_#{function}")
    PlannerService.new
    .plan_for(activities, start_, start_date, end_, end_date, self.kind)
  end

  def single_day?
    !self.start_date.nil? && self.start_date == self.end_date
  end

  def kind
    self.details[:kind]
  end

  def details
    # Traded in sliiiiight amount of performance/memory
    # to decrease significantly Geocoding queries.
    cities = []
    countries = []
    continents = []

    unless (self.start_destination.nil? || self.start_destination.empty?)
      cities << self.start_city
      countries << self.start_country
      continents << self.start_continent
    end

    unless (self.end_destination.nil? || self.end_destination.empty?)
      cities << self.end_city
      countries << self.end_country
      continents << self.end_continent
    end

    # in City (if everything happens in same city)
    cities += self.activities.map(&:city)
    return {kind: :city, where: cities.first} if cities.uniq.length == 1

    # in Country (if everything happends in same country)
    countries += self.activities.map(&:country)
    return {kind: :country, where: countries.first} if countries.uniq.length == 1

    continents += self.activities.map(&:continent)
    continents.uniq!

    return {kind: :continent, where: continents.first} if continents.length == 1
    return {kind: :bicontinent, where: "#{continents.first} - #{continents.last}"} if continents.length == 2
    return {kind: :global}
  end

  ## Explanation of functions below :
  # When someone asks for the data (city/country/continent)
  # we return the cached value.
  # If cache is empty, we compute and cache all 3 components
  # values for future use.
  # Repeat for all 3 components for both start and end

  def start_address
    return nil if self.kind == :city
    start_destination if start_destination != start_city
  end

  # TODO: Metaprog all those away.
  def start_city
    cache_start_components if (start_city_cache.nil? && start_destination.present?)
    return start_city_cache
  end

  # TODO: Metaprog all those away.
  def start_country
    cache_start_components if (start_country_cache.nil? && start_destination.present?)
    return start_country_cache
  end

  # TODO: Metaprog all those away.
  def start_continent
    cache_start_components if (start_continent_cache.nil? && start_destination.present?)
    return start_continent_cache
  end

  def end_address
    return nil if self.kind == :city
    end_destination if end_destination != end_city
  end

  # TODO: Metaprog all those away.
  def end_city
    cache_end_components if (end_city_cache.nil? && end_destination.present?)
    return end_city_cache
  end

  # TODO: Metaprog all those away.
  def end_country
    cache_end_components if (end_country_cache.nil? && end_destination.present?)
    return end_country_cache
  end

  # TODO: Metaprog all those away.
  def end_continent
    cache_end_components if (end_continent_cache.nil? && end_destination.present?)
    return end_continent_cache
  end

private

  # TODO: Metaprog all those away.
  def cache_start_components
    if start_destination.empty? # Case: removal of start_destination
      update_columns(
          start_city_cache: nil,
          start_country_cache: nil,
          start_continent_cache: nil
        )
    else # Case: update of start_destination
      start_components = LocationService.new.full_info(start_destination)
      update_columns(
        start_city_cache: start_components[:city],
        start_country_cache: start_components[:country],
        start_continent_cache: start_components[:continent]
      )
    end
  end

  # TODO: Metaprog all those away.
  def cache_end_components
    if end_destination.empty? # Case: removal of end_destination
      update_columns(
          end_city_cache: nil,
          end_country_cache: nil,
          end_continent_cache: nil
        )
    else # Case: update of end_destination
      end_components = LocationService.new.full_info(end_destination)
      update_columns(
        end_city_cache: end_components[:city],
        end_country_cache: end_components[:country],
        end_continent_cache: end_components[:continent]
      )
    end
  end

  ### Validators ###

  def start_date_is_a_date_or_nil
    if start_date.present?
      if ![Date, DateTime].include? start_date.class
        errors.add(:start_date, "n'est pas une date valide.")
      end
    end
  end

  def end_date_is_a_date_or_nil
    if end_date.present?
      if ![Date, DateTime].include? end_date.class
        errors.add(:end_date, "n'est pas une date valide.")
      end
    end
  end

  def start_date_is_valid
    if start_date.present?
      if start_date < updated_at
        errors.add(:start_date, "ne peut pas être antérieure à aujourd'hui")
      end
    end
  end

  def end_date_is_valid
    if start_date.present?
      if end_date.present?
        if end_date < start_date
          errors.add(:start_date, "ne peut pas être antérieure à la date de départ")
        end
      end
    end
  end
end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController
  before_action :find_roadmap, only: [:edit, :update, :destroy, :show]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @roadmaps = policy_scope(Roadmap).where("user_id = ?", current_user.id)
  end

  def show
    authorize(@roadmap)
  end

  # New doesn't exist. You want a new one => Create > Edit

  def create
    @roadmap = current_user.roadmaps.new
    authorize @roadmap
    if @roadmap.save
      redirect_to edit_roadmap_path(@roadmap)
    else
      flash[:alert] = "Sorry, we encountered a problem."
      redirect roadmaps_path
    end
  end

  def update
    @roadmap.update(roadmap_params)
    authorize @roadmap
    if @roadmap.save
      redirect_to @roadmap
    else
      render 'edit'
    end
  end

  def edit
    authorize @roadmap
    experiences = current_user.wishlisted_experiences
    experiences.uniq.sort! { |exp| -exp.average_rating }
    @groups = experiences.group_by { |e| e.country }
    @groups = @groups.each { |country, g| @groups[country] = g.group_by { |e| e.city } }
  end

  def destroy
    authorize @roadmap
    @roadmap.destroy
  end

  def send_roadmap
    @roadmap = Roadmap.find(params[:roadmap_id])
    authorize @roadmap
    UserMailer.itinerary(current_user, @roadmap).deliver_now
    flash[:mail] = "Votre itinéraire vous a été envoyé par email"
    redirect_to @roadmap
  end

private

  def find_roadmap
    @roadmap = Roadmap.find(params[:id])
  end

  def roadmap_params
    params.require(:roadmap).permit(:user_id, :start_date, :end_date, :start_destination, :end_destination, :travellers_num)
  end
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
  def title(roadmap)
    start = "Mon voyage"

    details = roadmap.details
    case details[:kind]
    when :city
      return "#{start} à #{details[:where]}"
    when :country
      return "#{start} #{(details[:where][-1] == 's') ? 'aux' : 'en'} #{details[:where]}"
    when :continent
      return "#{start} en #{details[:where]}"
    when :bicontinent
      return "#{start} #{details[:where]}"
    when :global
      return "#{start} autour du globe"
    else
      return "#{start}"
    end
  end
end

app/views/roadmaps/_schedule.html.erb
Feuille de route :
<%= flexible_content_tag :ul do %>
  <% schedule.each do |day|%>
    <% if day.any? { |k, v| k != :unscheduled && v.present? } || day[:unscheduled].any? { |_k, v| v.present? } %>
      <%= flexible_content_tag :li do %>
        <%# Find the date of the day we're rendering (checking the "planned_on" date of its 1st activity) %>
        <%= day.flatten.flatten.find { |a| a.is_a? Activity}.planned_on.to_formatted_s(:long) %>
        <%= flexible_content_tag :ul, class: "day" do%>
          <%= flexible_content_tag :li do %>
            <%= "Matin :" unless day[:morning].empty? %>
            <%= flexible_content_tag :ul, class: "morning" do %>
              <% day[:morning].each do |activity| %>
                <%= flexible_content_tag :li, "#{activity.title} <br>#{icon "map-marker"} [ #{activity.address} ]".html_safe %>
              <% end %>
            <% end %>
          <% end %>
          <%= flexible_content_tag :li do %>
            <%= "Déjeuner :" unless day[:midday].empty? %>
            <%= flexible_content_tag :ul, class: "midday" do %>
              <% day[:midday].each do |activity| %>
                <%= flexible_content_tag :li, "#{activity.title} <br>#{icon "map-marker"} [ #{activity.address} ]".html_safe %>
              <% end %>
            <% end %>
          <% end %>
          <%= flexible_content_tag :li do %>
            <%= "Après-midi :" unless day[:afternoon].empty? %>
            <%= flexible_content_tag :ul, class: "afternoon" do %>
              <% day[:afternoon].each do |activity| %>
                <%= flexible_content_tag :li, "#{activity.title} <br>#{icon "map-marker"} [ #{activity.address} ]".html_safe %>
              <% end %>
            <% end %>
          <% end %>
          <%= flexible_content_tag :li do %>
            <%= "Soir :" unless day[:evening].empty? %>
            <%= flexible_content_tag :ul, class: "evening" do %>
              <% day[:evening].each do |activity| %>
                <%= flexible_content_tag :li, "#{activity.title} <br>#{icon "map-marker"} [ #{activity.address} ]".html_safe %>
              <% end %>
            <% end %>
          <% end %>
          <%= flexible_content_tag :li do %>
            <%= "Nuit :" unless day[:night].empty? %>
            <%= flexible_content_tag :ul, class: "night" do %>
              <% day[:night].each do |activity| %>
                <%= flexible_content_tag :li, "#{activity.title} <br>#{icon "map-marker"} [ #{activity.address} ]".html_safe %>
              <% end %>
            <% end %>
          <% end %>
          <%= flexible_content_tag :li do %>
            <%= "Sélection de :" unless day[:unscheduled].none? { |k, v| v.present? } %>
              <%= flexible_content_tag :ul do %>
                  <%= flexible_content_tag :li do %>
                    <%= "Bars :" unless day[:unscheduled][:bars].empty? %>
                    <%= flexible_content_tag :ul do %>
                      <% day[:unscheduled][:bars].each do |bar| %>
                        <%= flexible_content_tag :li, "#{bar.title}<br>#{icon "map-marker"} [ #{bar.adress} ]" %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= flexible_content_tag :li do %>
                    <%= "Restaurants :" unless day[:unscheduled][:restaurants].empty? %>
                    <%= flexible_content_tag :ul do %>
                      <% day[:unscheduled][:restaurants].each do |rest| %>
                        <%= flexible_content_tag :li, "#{rest.title}<br>#{icon "map-marker"} [ #{rest.adress} ]" %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= flexible_content_tag :li do %>
                    <%= "Activités de jour :" unless day[:unscheduled][:occupations].empty? %>
                    <%= flexible_content_tag :ul do %>
                      <% day[:unscheduled][:occupations].each do |occ| %>
                        <%= flexible_content_tag :li, "#{occ.title}<br>#{icon "map-marker"} [ #{occ.adress} ]" %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= flexible_content_tag :li do %>
                    <%= "Activités de nuit :" unless day[:unscheduled][:nightlife].empty? %>
                    <%= flexible_content_tag :ul do %>
                      <% day[:unscheduled][:nightlife].each do |night| %>
                        <%= flexible_content_tag :li, "#{night.title}<br>#{icon "map-marker"} [ #{night.adress} ]" %>
                      <% end %>
                    <% end %>
                  <% end %>
                  <%= flexible_content_tag :li do %>
                    <%= "Hôtels :" unless day[:unscheduled][:hotels].empty? %>
                    <%= flexible_content_tag :ul do %>
                      <% day[:unscheduled][:hotels].each do |hotel| %>
                        <%= flexible_content_tag :li, "#{hotel.title}<br>#{icon "map-marker"} [ #{hotel.adress} ]" %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
        <% end %>
      <% end %>
    <% end %>
<% end %>
<%= flexible_content_tag :ul do %>
  <%= flexible_content_tag :li do %>
    <%= "Adresses à consulter :" unless unplanned.empty? %>
    <%= flexible_content_tag :ul do %>
      <% unplanned.each do |activity| %>
        <% date = (activity.planned_on.day.to_s) if activity.planned_on %>
        <% date += "/" if activity.planned_on %>
        <% date += (activity.planned_on.month.to_s) if activity.planned_on %>
        <% date += "/" if activity.planned_on %>
        <% date += (activity.planned_on.year.to_s)[-2..-1] if activity.planned_on %>
        <%= flexible_content_tag :li, "[#{date}] #{activity.title} <br>#{icon "map-marker"} [ #{activity.address} ]".html_safe %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/roadmaps/edit.html.erb
<% display = nil %>
<% display_counter = nil %>
<% display = "display:none;" if @roadmap.kind == :city %>
<% display_counter = "display:none;" unless @roadmap.kind == :city %>
<%# see later comments about start point/end point%>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4">
      <%= simple_form_for @roadmap do |f| %>
        <div class="parameters">
          <h3 style="text-align: center;">Construisez votre itinéraire</h3>
          <div class="row input_place_roadmap" style="<%= display %>">
            <div class="formulaire col-lg-6">
              <%# When travelling in a city: use the first Experience as start point. %>
              <%= f.input :start_destination, label: 'Départ', placeholder: "Où ?" %>
            </div>
            <div class="formulaire col-lg-6">
              <%# When travelling in a city: use the last Experience as end point. %>
              <%= f.input :end_destination, label: 'Arrivée', placeholder: "Où ?" %>
            </div>
          </div>
          <div class="row input_place_roadmap_placeholder" style="text-align: center;<%= display_counter %>">
            <div class="col-lg-12">
              <p>Vous être en train de construire un voyage pour la ville de</p>
              <p id="roadmap_city" style="font-weight: bold;"><%= @roadmap.details[:where] %></p>
            </div>
          </div>
          <div class="row">
            <div class="formulaire col-lg-6">
                <%= f.input :start_date, label: 'Du ', as: :bootstrap_datepicker, placeholder: "Quand ?" %>
            </div>
            <div class="formulaire col-lg-6">
                <%= f.input :end_date, label: 'Au ', as: :bootstrap_datepicker, placeholder: "Quand ?" %>
            </div>
          </div>
        </div>
        <div class="itinerary">
          <div class="to-see">
            <% @roadmap.activities.each do |activity| %>
              <%= render 'shared/inline_activity', activity: activity, display_date: !@roadmap.single_day? %>
            <% end %>
          </div>
        </div>
        <div class="parameters" style="padding: 0; height: 40px; margin-top: 5px;">
          <div class="row">
            <div class="formulaire col-lg-12">
             <%= f.submit "Lancer mon itinéraire", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="col-lg-8">
        <div class="experiences-roadmap">
          <% if @groups.length == 0 %>
            <h3 style="text-align:center; color: grey;">Ajoutez des coups de coeur à vos favoris pour pouvoir créer un itinéraire</p>
          <% else %>
            <div class="container-fluid">
              <% @groups.sort_by { |_, c| -c.reduce(0){ |a, e| a + e.length } }.each do |country, content| %>
                <div class="row">
                  <h3><%= country %></h3>
                  <div class="container_fluid" style="padding-left:30px;">
                    <% content.sort_by { |_,e| -e.length }.each do |city, experience| %>
                      <div class="row">
                        <h3><%= city %></h3>
                        <% experience.each do |experience| %>
                          <div class="col-xs-12 col-sm-4">
                            <%= render "shared/card", experience: experience %>
                            <% path_to_create_activity = roadmap_experience_activities_path(@roadmap, experience) %>
                            <% path_to_create_activity += "?single_day=true" if @roadmap.single_day? %>
                            <%= link_to icon('plus'), path_to_create_activity, class: "add-experience", id: "add-experience-#{experience.id}", remote: true, method: :post %>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

<% content_for :after_js do %>
<script>
  $(document).ready(function(){

  google.maps.event.addDomListener(window, 'load', function() {
    initializeAutocomplete('roadmap_start_destination');
  });
  google.maps.event.addDomListener(window, 'load', function() {
    initializeAutocomplete('roadmap_end_destination');
  });

    $(".unplanner").click(function(e){
      e.preventDefault();
      var activityID = $(this)[0].id;
      $.ajax({
        method: "PATCH",
        url: "/activities/"+activityID.split("-")[1],
        data: { planned_on: "nil" }
      }).done(function(e){
        console.log("activity-"+activityID.split("-")[1]+"-date")
        $("#activity-"+activityID.split("-")[1]+"-date").val("");
      });
    });

    $(".bootstrap-datepicker.activity-date").datepicker({
      isRTL: false,
      autoclose:true,
      language: 'fr'
    });
  });
</script>
<% end %>

app/views/roadmaps/index.html.erb
<div class="container search-form">
  <div class="search-center">
    <h2>Mes itinéraires :</h2>
  </div>
</div>

<div class="block-contain">
  <div class="container search-form">
    <div class="row card-container">
      <% @roadmaps.each do |roadmap| %>
        <div class="col-xs-12 col-md-4 polaroid-center">
          <%= render "shared/polaroid", roadmap: roadmap, planning: roadmap.planning %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="banner-bottom-cta">
    <%= link_to roadmaps_path, method: :post, class: "btn btn-primary" do%>
        <%= icon "globe" %> Créer un itinéraire.
    <% end %>
  </div>
</div>

<% content_for :after_js do %>
  <script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<% end %>

app/views/roadmaps/show.html.erb
<% planning = @roadmap.planning %>
<% addresses = planning[:itinerary] %>

<div class="container-fluid">
  <div class="row">
    <div class="block-left col-md-6">
      <div class="row" style="position: relative; display: flex; flex-direction: column; margin-right: 25px; margin-left: 25px;">
      <div class="text-center title">
        <h2>
          <%= title(@roadmap) %>
          <% if policy(@roadmap).edit? %>
            <%= link_to icon("pencil"), edit_roadmap_path(@roadmap), class: "icon-controlled-access" %>
          <% end %>
          <% if policy(@roadmap).send_roadmap? %>
            <%= link_to icon("envelope-o"), roadmap_send_path(@roadmap), class: "icon-controlled-access" %>
          <% end %>
        </h2>
        </div>
        <div class="text-and-author" style="margin-top:-20px; background-color: #F4F4F4 ;height: 100px; display: flex; align-items: center; justify-content: space-around; flex-wrap: wrap;">
        <% planning[:itinerary].each_with_index do |city, index| %>
          <div class="city"><%= city %></div>
          <% unless index == (planning[:itinerary].length-1) %>
            <%= icon("long-arrow-right").html_safe %>
          <% end %>
        <% end %>
        </div>
        <div class="reviews col-md-12" style="position: relative;">
          <%= render "schedule", schedule: planning[:schedule], unplanned: @roadmap.activities %>
          <div style="position: absolute; top: 10px; right: 25px;">
            <%= render "shared/facebook_share", url: roadmap_url(@roadmap), title: title(@roadmap), description: "Le voyage de #{@roadmap.user.first_name.capitalize}", photo: image_url("hiker-#{(1..2).to_a.sample}.jpg") %>
          </div>
        </div>
      </div>
      </div>
      <div class="block-right block-fixed col-md-6">
        <div class="row">
            <div id="map-canvas">
              <div id="map" style="height: calc(100vh-70px);"></div>
            </div>
      </div>
    </div>
  </div>
</div>


<% content_for :after_js do %>
  <script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
  <script>
  var styleArray = [{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2e5d4"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#c5dac6"}]},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{"featureType":"road","elementType":"all","stylers":[{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#c5c6c6"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#e4d7c6"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#fbfaf7"}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"color":"#acbcc9"}]}]
  initMap();
function initMap() {
  // Instantiate a directions service.
  var directionsService = new google.maps.DirectionsService;

  // Create a map, apply our custom style on it.
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 13,
    style: styleArray
  });

  var listener = google.maps.event.addListener(map, "idle", function() {
    <% if addresses.uniq.length == 1 %>
      map.setZoom(12);
    <% end %>
    google.maps.event.removeListener(listener);
  });


  // Create a renderer for directions and bind it to the map.
  var directionsDisplay = new google.maps.DirectionsRenderer({map: map});

  // Display the route between the initial start and end selections.
  calculateAndDisplayRoute(directionsDisplay, directionsService);
}

function calculateAndDisplayRoute(directionsDisplay, directionsService) {

  directionsService.route({
    origin: "<%= addresses.first %>",
    destination: "<%= addresses.last %>",
    travelMode: google.maps.TravelMode.WALKING,
    // TODO: Add a way to pick between Walking/Driving/...
    <% if addresses.length > 2 %>
    waypoints: [
                <% addresses[1...-1].each do |wp| %>
                   {location: "<%= wp %>", stopover: false},
                <% end %>
               ]
    <% end %>
  }, function(response, status) {
    // Route the directions
    if (status === google.maps.DirectionsStatus.OK) {
      // Google warnings handling (deactivated for now.)
      //document.getElementById('steps').innerHTML =
        //  '<b>' + response.routes[0].warnings + '</b>';
      directionsDisplay.setDirections(response);
    } else {
      // Error handling (deactivated for now.)
      // document.getElementById('steps').innerHTML =
         // '<b>' + 'Directions request failed due to ' + status + '</b>';
    }
  });
}
  </script>
<% end %>