config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#landing_page'

  post "/" => 'pages#save_email'

  get "contact" => "pages#contact"
  post "contact" => "pages#contact_mail"

  get "cgu" => "pages#cgu"

  mount Attachinary::Engine => "/attachinary"

  resources :experiences do
    post "send_experience" => "experiences#send_experience", as: 'send'
    resources :ratings, only: [:create]
    resources :wishlists, only: [:create]
  end

  post "gps_coordinates" => "images#get_gps"

  resources :roadmaps do
    get "send_roadmap" => "roadmaps#send_roadmap", as: 'send'
    resources :experiences do
      resources :activities, only: [:create]
    end
  end

  resources :roadmaps
  resources :activities, only: [:update, :destroy] do
    post "up" => "activities#up"
    post "down" => "activities#down"
  end

  get "my_experiences" => "experiences#my_experiences"

  resources :wishlists, only: [:index, :destroy]
  resources :ratings, only: [:destroy]
 end

app/views/shared/_card.html.erb
<% deletable ||= false %>
<div class="card_wrapper" style="position:relative;">
  <%= link_to experience do %>
    <div class="card text-center" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.4) 0%, rgba(0,0,0,0.3) 100%), url('<%= cl_image_path experience.photos[0].path, size: "500x300", crop: :fill; %>');">
      <div class="card-user">
        <%= cl_image_tag experience.user.avatar.path, class:"avatar-radius", size: "40x40",crop: :fill, gravity: :faces, title: experience.user.first_name %>
      </div>
      <span class="rating">
        <%= render "shared/rating", rating: experience.average_rating %>
      </span>
      <p class="card-category">
        <%= title_category(experience.category) %>
      </p>
      <div class="card-description">
        <h3>
          <% if experience.title.length > 30 %>
            <%= "#{experience.title[0...27]}..." %>
          <% else %>
            <%= experience.title %>
          <% end %>
        </h3>
        <p>
          <% if experience.description.length > 100 %>
            <%= "#{experience.description[0...97]}..." %>
          <% else %>
            <%= experience.description %>
          <% end %>
        </p>
      </div>
      <div class="card-location">
        <i class="fa fa-map-marker"></i><p><%= experience.city %>, <%= experience.country %></p>
      </div>
    </div>
  <% end %>
  <div style="position: absolute; top: 30px; right: 15px; font-size: 20pt;">
    <% if user_signed_in? %>
      <%= render'wishlists/heart',
        wished: current_user.wishlisted_experiences.include?(experience),
        wishlist: experience.wishlists.find_by(user: current_user),
        experience: experience,
        notext: true,
        delete_after: deletable %>
    <% end %>
  </div>
</div>

app/views/shared/_experience_form.html.erb
<% id ||= 'experience' %>
<%# To allow Gmaps JS to work its magic even when we call the partial several times %>
<%# To allow Attachinary to work its magic even when we call the partial several times %>

<%= simple_form_for experience do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: "Titre", placeholder: "Donnez envie de découvrir votre moment" %>
  <%= f.input :category_id,
              as: :select,
              label: "Catégories",
              collection: Category.as_tree,
              include_blank: "Choisissez une catégorie et sous-catégorie",
              value_method: :id,
              label_method: ->(c) do
                if c.parent_category.nil?
                  c.title
                else
                  "| -- #{c.title}"
                end
              end %>
  <%= f.input :description, label: "Description", placeholder: "Décrivez votre coup de coeur, pourquoi est-ce un coup de coeur ?" %>
  <%= f.input :url, label: "Site web", placeholder: "Entrez un lien internet" %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-8">
        <%= f.input :photos, as: :attachinary, input_html: {id: "#{id}_attachinary_input"} %>
      </div>
      <div class="col-sm-4">
        <%= f.input :price, label: "Prix", placeholder: "Prix par pers.", input_html: {min: 0}%>
      </div>
    </div>
  </div>

  <%= f.input :address, label: "Adresse", input_html: {id: "#{id}_autocomplete"}, placeholder: "Entrez un endroit" %>
  <hr>
  <%= f.button :submit, "Partager !", class:'btn btn-success btn-block' %>
<% end %>

<% content_for :after_js do %>
  <script>
    $(document).ready(function(){

    google.maps.event.addDomListener(window, 'load', function() {
      initializeAutocomplete("<%= j id %>_autocomplete");
    });

    $("#<%= j "#{id}_attachinary_input" %>").bind('fileuploaddone', function (e, data) {
      if ($("#<%= j id %>_autocomplete").val() == "") {
        $.post({
          url: "<%= j gps_coordinates_path %>",
          data: {public_id: data.attachinary.files[data.attachinary.files.length -1].public_id}
        }).done(function(res) {
          if(response.address != null){
            $("#<%= j id %>_autocomplete").val(response.address);
          };
        });
      };
    });
   });
  </script>
<% end %>

app/views/shared/_facebook_share.html.erb
<div id="fb-root"></div>

<div class="fb-share-button" data-href="http://share-your-trip.herokuapp.com" data-layout="button_count"></div>


<% content_for :head do %>
  <meta property="fb:app_id"      content="<%= ENV['FB_ID'] %>"/>
  <meta property="og:url"         content="<%= url %>" />
  <meta property="og:type"        content="website" />
  <meta property="og:title"       content="<%= title %>"/>
  <meta property="og:description" content="<%= description %>" />
  <meta property="og:image"       content="<%= photo %>" />
<% end %>

<% content_for :after_js do %>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '<%= ENV['FB_ID'] %>',
        xfbml      : true,
        version    : 'v2.5'
      });
    };

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=<%= ENV['FB_ID'] %>";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash[:mail] %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:mail] %>
  </div>
<% end %>
<% if false %>
  <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="Footer-credits">
  <span class="Footer-credit"><a href="#" data-lang="fr">|  À propos  |</a></span>
  <span class="Footer-credit"><%= link_to "|  Nous contacter  |", contact_path %></span>
  <span class="Footer-credit"><%= link_to "|  Vie privée & Sécurité  |", cgu_path %></span>
</div>
<br>
<div class="lucky">
|  Fait avec <span class="luckycolor">♣</span> à Bordeaux  |
</div>

app/views/shared/_infowindow.html.erb
<div style="display: flex">
  <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; margin-right: 15px;">
    <div><%= link_to experience.title, experience %></div>
    <div class="average-rating">
          <%= render "shared/rating", rating: experience.average_rating %>
    </div>
  </div>
  <div>
   <%= link_to experience do %>
    <%= cl_image_tag(experience.photos[0].path, height: 50) %>
   <% end %>
  </div>
</div>

app/views/shared/_inline_activity.html.erb
<div class="roadmap-activity" data-pid=<%= activity.position %> data-mid=<%= activity.id %>>
  <div class="left">
    <%= link_to icon('times'), activity_path(activity), method: :delete, remote: true, class: "remove-experience remove-experience-#{activity.id}" %>
    <p><%= activity.experience.title %></p>
  </div>
  <div class="right">
    <div class="date-pick" <%= "style='display: none;'".html_safe if !display_date %>>
      <% if activity.planned_on.present? %>
        <input class="bootstrap-datepicker activity-date" id="activity-<%= activity.id %>-date" value="<%= activity.planned_on.day %>/<%= activity.planned_on.month %>/<%= activity.planned_on.year %>">
      <% else %>
        <input class="bootstrap-datepicker activity-date" id="activity-<%= activity.id %>-date" placeholder="Quand ?">
      <% end %>
    </div>
    <div class="positioner" style="margin-left:10px; display: flex; flex-direction: column; justify-content: center;">
      <%= link_to icon("chevron-up"), activity_up_path(activity), style:"margin-bottom:-5px;", method: :post, remote: true %>
      <%= link_to icon("chevron-down"), activity_down_path(activity), style:"margin-top:-5px;", method: :post, remote: true %>
    </div>
  </div>
</div>

app/views/shared/_map.html.erb
<div id="map"></div>

<% content_for :after_js do %>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
  <script>
  var styleArray = [{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2e5d4"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#c5dac6"}]},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{"featureType":"road","elementType":"all","stylers":[{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#c5c6c6"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#e4d7c6"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#fbfaf7"}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"color":"#acbcc9"}]}]
  var gmap = new google.maps.Map(document.getElementById('map'), {
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    styles: styleArray,
    zoom: 14
  });
  displayOnMap(gmap);

  function displayOnMap(gmap){
    var markers = [];
    var infowindows = [];

    <% @close_by.to_a.insert(0, @experience) %>

    <% @close_by.each_with_index do |experience, index| %>

      infowindows[<%= index %>] = new google.maps.InfoWindow({
        content: '<%= j render("shared/infowindow", experience: experience) %>'
      });

      markers[<%= index %>] = new google.maps.Marker({
        position: {
          lat: <%= experience.latitude %>,
          lng: <%= experience.longitude %>,
        },
        map: gmap,
      });

      markers[<%= index %>].addListener('click', function() {
        for(var i=0; i<infowindows.length; i++){
          infowindows[i].close();
        }
        infowindows[<%= index %>].open(gmap, this);
        infowindows[<%= index %>].position = this;
      });

    <% end %>

    google.maps.event.trigger(markers[0], 'click');
    gmap.setCenter(markers[0].position);
  };
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<% white ||= false %>
<div class="navbar-wagon <%= "navbar-wagon-white" if white %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <% if white %>
      <%= image_tag "logo-white.png" %>
    <% else %>
      <%= image_tag "logo-grey.jpg" %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <button type="button" class="navbar-wagon-item navbar-wagon-link navbar-wagon-button" data-toggle="modal" data-target="#addExperience">
        Publier un <%= icon("heart") %>
      </button>

      <%= link_to "Créer un itinéraire #{icon "globe"}".html_safe, roadmaps_path, method: :post, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button"%>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
            <span style="margin-right: 10px; color: grey;"><%= current_user.first_name %></span>
            <%= cl_image_tag current_user.avatar.path, size: "40x40", crop: :fill, class: "avatar avatar-bordered avatar-large" %>
          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to my_experiences_path do %>
                <i class="fa fa-heart"></i> <%= t ".mes coups de coeur", default: "Mes coups de coeur" %>
              <% end %>
            </li>
            <li>
              <%= link_to wishlists_path do %>
                <i class="fa fa-heart"></i> <%= t ".mes favoris", default: "Mes Favoris" %>
              <% end %>
            </li>
            <li>
              <%= link_to roadmaps_path do %>
                <i class="fa fa-globe"></i> <%= t ".mes itinéraires", default: "Mes Itinéraires" %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-user"></i>  <%= t ".sign_out", default: "Éditer mon profil" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <!-- Login text link -->
      <%= link_to "Publier un #{ icon("heart")}".html_safe, new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn" %>
      <%= link_to "Créer un itinéraire #{icon "globe"}".html_safe, roadmaps_path, method: :post, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn" %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn" %>
    <% end %>

  </div>

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to roadmaps_path, method: :post do %>
              Créer un itinéraire <%= icon "globe" %>
            <% end %>
          </li>
          <li>
            <%= link_to "", "data-toggle": "modal", "data-target":"#addExperience" do %>
              Publier un <%= icon("heart") %>
            <% end %>
          </li>
          <hr>
          <li>
            <%= link_to my_experiences_path do %>
              <p style="text-align:right"><%= t ".mes coups de coeur", default: "Mes coups de coeur " %> <i class="fa fa-heart"></i></p>
            <% end %>
          </li>
          <li>
            <%= link_to wishlists_path do %>
              <p style="text-align:right"><%= t ".mes favoris", default: "Mes Favoris " %> <i class="fa fa-star"></i></p>
            <% end %>
          </li>
          <li>
            <%= link_to roadmaps_path do %>
              <p style="text-align:right"><%= t ".mes itinéraires", default: "Mes Itinéraires " %> <i class="fa fa-globe"></i></p>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path(current_user) do %>
              <p style="text-align:right"><i class="fa fa-user"></i>  <%= t ".sign_out", default: "Éditer mon profil" %></p>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <p style="text-align:right"><%= t ".sign_out", default: "Log out " %> <i class="fa fa-sign-out"></i></p>
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn" %>
    <% end %>
  </div>

</div>

<div class="modal fade" id="addExperience" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Mon coup de Coeur</h4>
      </div>
      <div class="modal-body input">
        <%= render "shared/experience_form", experience: Experience.new %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_polaroid.html.erb
<%= link_to roadmap do %>
<div class="polaroid text-center">
  <% if roadmap.start_destination && roadmap.end_destination %>
  <div id="map-canvas" style="margin: 10px auto; height: 260px; width:260px;">
    <div id="map-<%= roadmap.id %>" style="height: 100%; width:100%"></div>
  </div>
  <% else %>
    <div style="margin: 10px auto; height: 260px; width:260px;">
      <%= image_tag "carnet.png", style: "width: 260px; height: 260px"%>
    </div>
  <% end %>
  <div class="polaroid-info">
    <div class="polaroid-cities">
      <h5><%= title(roadmap) %></h5>
    </div>
    <div class="polaroid-dates">
      <% unless roadmap.start_date.nil? || roadmap.end_date.nil? %>
        <div><%= roadmap.start_date.to_s(:rfc822) %></div>
        <div><%= roadmap.end_date.to_s(:rfc822)%></div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

<% content_for :after_js do %>
  <script>
  var styleArray = [{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2e5d4"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#c5dac6"}]},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{"featureType":"road","elementType":"all","stylers":[{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#c5c6c6"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#e4d7c6"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#fbfaf7"}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"color":"#acbcc9"}]}]
  initMap();
  <% addresses = planning[:itinerary] %>
function initMap() {
  // Instantiate a directions service.
  var directionsService = new google.maps.DirectionsService;

  // Create a map, apply our custom style on it.
  var map = new google.maps.Map(document.getElementById('map-<%= roadmap.id %>'), {
    zoom: 12,
    style: styleArray,
    disableDefaultUI: true
  });
  map.setOptions({draggable: false, zoomControl: false, scrollwheel: false, disableDoubleClickZoom: true});
  // Create a renderer for directions and bind it to the map.
  var directionsDisplay = new google.maps.DirectionsRenderer({map: map <%= j ", suppressMarkers: true" if addresses.length == 1%>});

  // Display the route between the initial start and end selections.
  calculateAndDisplayRoute(map, directionsDisplay, directionsService);

}

function calculateAndDisplayRoute(map, directionsDisplay, directionsService) {

  directionsService.route({
    origin: "<%= addresses.first %>",
    destination: "<%= addresses.last %>",
    // TODO: Add a way to pick between Walking/Driving/...
    <% if addresses.length > 2 %>
    waypoints: [
                <% addresses[1...-1].each do |wp| %>
                  {location: "<%= wp %>", stopover: false},
                <% end %>
               ],
    <% end %>
    travelMode: google.maps.TravelMode.WALKING
  }, function(response, status) {
    // Route the directions
    if (status === google.maps.DirectionsStatus.OK) {
      // Google warnings handling (deactivated for now.)
      //document.getElementById('steps').innerHTML =
        //  '<b>' + response.routes[0].warnings + '</b>';
var listener = google.maps.event.addListener(map, "idle", function() {
    <% if addresses.uniq.length == 1 %>
      map.setZoom(12);
      console.log("Ay");
    <% end %>
    google.maps.event.removeListener(listener);
  });
      directionsDisplay.setDirections(response);
    } else {
      // Error handling (deactivated for now.)
      // document.getElementById('steps').innerHTML =
         // '<b>' + 'Directions request failed due to ' + status + '</b>';
    }
  });
}
  </script>
<% end %>

app/views/shared/_rating.html.erb
<% (rating).times do %>
  <%= icon("star") -%>
<% end %>
<% (5-rating).times do %>
  <%= icon("star-o") -%>
<% end %>

app/views/shared/_review.html.erb
<div class="review" id="review_<%= locals[:review].id %>">
  <div class="author">
    <%= cl_image_tag locals[:review].user.avatar.path, crop: :fill, size: "30x30", class: "avatar", gravity: :face %>
    <span class="username"><%= locals[:review].user.first_name.capitalize %></span>
  </div>
  <div class="review-content">
    <%= locals[:review].review %>
  </div>
  <div class="rating">
    <%= render "shared/rating", rating: locals[:review].rating %>
  </div>
  <% if policy(locals[:review]).destroy? %>
    <%= link_to rating_path(locals[:review]), method: :delete do %>
      <%= icon('times') %>
    <% end %>
  <% end %>
</div>

app/views/shared/_review_form.html.erb
<div class="review" id="form">
<%= simple_form_for [locals[:parent], locals[:review]] do |f| %>
  <div class="author">
    <%= cl_image_tag locals[:review].user.avatar.path, crop: :fill, size: "30x30", class: "avatar", gravity: :face %>
    <span class="username"><%= current_user.first_name.capitalize %></span>
  </div>
  <div class="review-content">
    <%= f.input :review, type: "textarea", input_html: { class: "input-content", rows: 2 }, label: false, placeholder: "Laisser un commentaire !" %>
  </div>
  <div class="input-rating">
  <%= f.input :rating,  as: :radio_buttons, label: false, error: false do%>
    <%= f.collection_radio_buttons :rating, (0..4).reverse_each, :succ, ->(a){false}, boolean_style: :inline, item_wrapper_tag: false do |b| %>
      <%= b.radio_button class: 'with-font' %>
      <%= b.label {""} %>
    <% end %>
  <% end %>
  </div>
  <%= f.button :button, class: "input-validate btn btn-primary ladda-button", "data-style": "contract" do %>
    <span class="ladda-label">Commenter</span>
  <% end %>
<% end %>
</div>

app/views/shared/_search_input.html.erb
<%# SEARCH INPUT ON EXPERIENCES/INDEX + HOME %>
<%# One per page due to ID regulation,       %>
<%# extract id to partial parameter and u go %>

<% noorder ||= false %>
<div class="index-search-field">

  <%= simple_form_for :search, url: experiences_path, method: :get, html: { class: 'form-search form-inline' } do |f| %>
    <%= f.input_field :address, id: "user_input_autocomplete_address", placeholder: "Où souhaitez-vous aller ?", class: "input-medium search-query" %>
    <%= f.submit "Chercher", class: "navbar-wagon-item navbar-wagon-link navbar-wagon-button btn btn-square" %>
    <% unless noorder %>
    <%= f.input :category_id,
        as: :select,
        label: false,
        class: "select form-control",
        collection: Category.as_tree,
        include_blank: "Choisissez une catégorie",
        value_method: :id,
        label_method: ->(c) do
          if c.parent_category.nil?
            c.title
          else
            "| -- #{c.title}"
          end
        end %>
      <%= f.input_field :sort,
        include_blank: "Trier par...",
        as: :select,
        collection: [:date, :note],
        label_method: ->(i){ {date: "Date", note: "Note moyenne"}[i] },
        class: "select form-control" %>
    <% end %>
  <% end %>

</div>

<% content_for :after_js do %>
  <script>
    $(document).ready(function(){

    google.maps.event.addDomListener(window, 'load', function() {
      initializeAutocomplete('user_input_autocomplete_address');
    });

   });
  </script>
<% end %>