config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#landing_page'

  post "/" => 'pages#save_email'

  get "contact" => "pages#contact"
  post "contact" => "pages#contact_mail"

  get "cgu" => "pages#cgu"

  mount Attachinary::Engine => "/attachinary"

  resources :experiences do
    post "send_experience" => "experiences#send_experience", as: 'send'
    resources :ratings, only: [:create]
    resources :wishlists, only: [:create]
  end

  post "gps_coordinates" => "images#get_gps"

  resources :roadmaps do
    get "send_roadmap" => "roadmaps#send_roadmap", as: 'send'
    resources :experiences do
      resources :activities, only: [:create]
    end
  end

  resources :roadmaps
  resources :activities, only: [:update, :destroy] do
    post "up" => "activities#up"
    post "down" => "activities#down"
  end

  get "my_experiences" => "experiences#my_experiences"

  resources :wishlists, only: [:index, :destroy]
  resources :ratings, only: [:destroy]
 end

app/models/experience.rb
require 'uri'

class Experience < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_many :ratings, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :users, through: :wishlists
  has_many :activities, dependent: :destroy
  has_many :roadmaps, through: :activities

  default_scope { order(created_at: :desc) }

  validates :title, presence: true
  validates :category, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :photos, presence: true
  validates :price, numericality: { min: 0, allow_blank: true }
  validate :valid_url

  has_attachments :photos, maximum: 3

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  after_save :cache, if: :address_changed?

  def self.search(search, experiences) # Second parameter needed to account for Pundit scope
    # TODO: Extract the three parts in respective methods.
    locate = LocationService.new
    results = experiences
    if search
      # Localization
      if !search[:address].blank?
        city = locate.city(search[:address]) # if it's not city it's a country
        if city.present? # city
          results = results.near(search[:address], 20)
        else # country
          country = locate.country(search[:address])
          results = results.select{ |e| e.country == country}
        end
      end

      # Category
      if !search[:category_id].blank?
        filter_category = Category.find(search[:category_id])
        results = results.select { |e| filter_category.with_children.include? e.category }
      end

      # Sorting/ordering
      sort = search[:sort]
      if sort == "note"
        # Best to worst // + to -
        results = results.sort { |e, f| f.average_rating - e.average_rating }
      else
        # Most recent to oldest // - to +
        results = results.sort { |e, f| e.created_at - f.created_at }
      end
    end

    results
  end

  def is_occupation?
    return !%W(Hébergement Restauration Bar/café Commerçant\ local)
      .map { |t| Category.find_by_title(t).with_children.flatten }
      .include?(self.category.title)
  end

  # Not used (yet?)
  def is_reusable?
    return self.category.title == "Hôtel"
  end

  def average_rating
    if self.ratings.length > 0
      sum = self.ratings.reduce(0) { |a, r| r.rating+a }
      return sum/self.ratings.length
    else
      return 3 # Average by default not to penalize new Experiences
    end
  end

  ## City/Country/Continent
  # Returns the cached value of the property
  # if cache doesn't exist yet, builds cache
  # for all three values.
  def city
    cache if self.city_cache.nil?
    return city_cache
  end

  def country
    cache if self.country_cache.nil?
    return country_cache
  end

  def continent
    cache if self.continent_cache.nil?
    return continent_cache
  end

private

  def cache
    data = LocationService.new.full_info(address)
    update_columns(
      city_cache: data[:city],
      country_cache: data[:country],
      continent_cache: data[:continent]
    )
  end

  def valid_url
  return if self.url == nil or self.url == ""
  uri = URI.parse(self.url)
  errors.add(:url, "n'est pas une URL valide.") unless uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    errors.add(:url, "n'est pas une URL valide.")
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :find_experience, only: [:edit, :update, :destroy, :show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @experiences = Experience.search(params[:search], policy_scope(Experience))
    @markers = Gmaps4rails.build_markers(@experiences) do |experience, marker|
      marker.lat experience.latitude
      marker.lng experience.longitude
    end
  end

  def show
    authorize @experience
    @close_by = @experience.nearbys(10)
    # Display close by experiences.
    if user_signed_in?
      @rating = current_user.ratings.new
      @rating.experience_id = @experience.id
      @wished = current_user.wishlisted_experiences.include? @experience
      @wishlist = @experience.wishlists.find_by(user: current_user)
    end
  end

  def new
    @experience = current_user.experiences.new
    authorize @experience
  end

  def create
    @experience = current_user.experiences.new(experience_params)
    authorize @experience
    if @experience.save
      redirect_to @experience
    else
      render 'new'
    end
  end

  def update
    @experience.update(experience_params)
    authorize @experience
    if @experience.save
      redirect_to @experience
    else
      render 'edit'
    end
  end

  def edit
    authorize @experience
  end

  def destroy
    authorize @experience
    if @experience.destroy
      redirect_to experiences_path
    else
      flash[:alert] = "Une erreur s'est produite."
      render @experience
    end
  end

  def my_experiences
    @experiences = policy_scope(Experience).where("user_id = ?", current_user)
    authorize @experiences
  end

  def send_experience
    @experience = Experience.find(params[:experience_id])
    authorize @experience
    UserMailer.experience(params[:send_experience][:recipient], experience_url(@experience)).deliver_now
    flash[:mail] = "Coup de coeur partagé à #{params[:send_experience][:recipient]}."
    redirect_to @experience
  end

private

  def find_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:user_id, :category_id, :price, :url, :description, :address, :title, photos: [])
  end

end

app/helpers/experiences_helper.rb
module ExperiencesHelper
  def title_category(category)
    if category.is_root?
      category.title
    else
      "#{category.parent_category.title}<br>(#{category.title})".html_safe
    end
  end
end

app/views/experiences/_review_form.html.erb
<div class="review">
<%= simple_form_for [locals[:parent], locals[:review]] do |f| %>
  <div class="author">
    <span class="username"><%= current_user.first_name.capitalize %></span>
  </div>
  <div class="review-content">
    <%= f.input :review, type: "textarea", input_html: { class: "input-content", rows: 2 }, label: false, placeholder: "Leave a review?", error: false %>
  </div>
  <div class="input-rating">
  <%= f.input :rating,  as: :radio_buttons, label: false, error: false do%>
    <%= f.collection_radio_buttons :rating, (0..4).reverse_each, :succ, ->(a){false}, boolean_style: :inline, item_wrapper_tag: false do |b| %>
      <%= b.radio_button class: 'with-font' %>
      <%= b.label {""} %>
    <% end %>
  <% end %>
  </div>
  <%= f.button :button, class: "input-validate btn btn-primary ladda-button", "data-style": "contract" do %>
    <span class="ladda-label">Submit</span>
  <% end %>
<% end %>
</div>

app/views/experiences/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2>Éditez votre coup de coeur.</h2>
      <%= render "shared/experience_form", experience: @experience, id: "edit_exp_autocomplete" %>
    </div>
  </div>
</div>

app/views/experiences/extract_address.js.erb
var address = "<%= @address %>";

app/views/experiences/index.html.erb
<% params[:search] ||= {} %>

<div class="container search-form">
  <div class="search-center" style="flex-direction: column;">
    <div class="search-center" style="background: none;">
      <%= render 'shared/search_input'%>
    </div>
  </div>
</div>


<div class="block-contain">
  <div class="container-fluid">
    <div class="row card-container">
      <% if @experiences.blank? %>
        <div style="display: flex; align-items: center; flex-direction: column;">
          <h2>Oups! Pas encore de coups de coeur partagés pour cette destination!</h2>
          <h3>Vous connaissez des grands voyageurs? Invitez-les à partager leurs coups de coeur avec nous!</h3>
        </div>
      <% else %>
        <% @experiences.each do |experience| %>
          <div class="col-xs-12 col-sm-4">
            <%= render "shared/card", experience: experience %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="banner-bottom-cta">
  <%= link_to my_experiences_path do %>
    <i class="fa fa-heart"></i> <%= t ".mes coups de coeur", default: "Mes coups de coeur" %>
  <% end %>
</div>

app/views/experiences/my_experiences.erb
<h2>INDEX</h2>

<% @experiences.each do |experience| %>
  <div class="experience">
    <p><%= experience.user.first_name %> <%= experience.user.last_name %> enjoyed :</p>
    <%= link_to experience do %>
      <h3><%= experience.title %></h3>
    <% end %>
    <p><%= experience.category %></p>
    <p><%= experience.description %></p>
    <p><%= experience.address %></p>
  </div>
<% end %>

app/views/experiences/my_experiences.html.erb
<div class="container search-form">
  <div class="search-center">
    <h2>Mes coups de coeur :</h2>
  </div>
</div>

<div class="block-contain" style="position: unset;">
  <div class="container-fluid">
    <div class="row card-container">
      <% @experiences.each do |experience| %>
        <div class="col-xs-12 col-sm-4">
          <%= render "shared/card", experience: experience %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="banner-bottom-cta">
    <%= link_to wishlists_path do %>
      <i class="fa fa-heart"></i> <%= t ".mes coups de coeur", default: "Mes coups de coeur" %>
    <% end %>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h2>Publiez votre coup de coeur.</h2>
      <%= render "shared/experience_form", experience: @experience, id: "new_exp_autocomplete" %>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<% content_for :title do %>
  <%= @experience.title %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="block-left col-md-6">
      <div class="row" style="display: flex; flex-direction: column; margin-right: 25px; margin-left: 25px;">
        <div class="text-and-author">
            <div class="experience-header">
              <div class="title">
                <h3>
                <%= @experience.title %>
                <% if policy(@experience).edit? %>
                  <%= link_to icon("pencil"), edit_experience_path(@experience), class: "icon-controlled-access" %>
                  <%= link_to icon("times"), @experience, method: :delete, class: "icon-controlled-access" %>
                <% end %>
                </h3>
              </div>
              <div class="rating" style="position: relative; display: flex; flex-direction: column;">
                <span class="average-rating">
                  <%= render "shared/rating", rating: @experience.average_rating %>
                </span>
                <div>
                <span style="position: absolute; left: 0; right: 0; text-align: center; font-weight: bold;">
                  <% if @experience.price %>
                    <%= @experience.price %>€/pers.
                  <% end %>
                </span>
                <span style="position: absolute; text-align: right; width: 150px; bottom: 0; right: 0;">
                  Publié le <% date = @experience.created_at %>
                  <%= date.strftime("#{date.day}/#{date.month}/#{date.year.to_s[-2..-1]}") %>
                </span>
                </div>
              </div>
            </div>

            <div class="experience-description">
              <%= @experience.description %>
            </div>
            <div class="author-details" style="position: relative; margin-top: 60px;">
              <% unless @experience.url.blank? %>
                <div style="position: absolute; top: -45px; right: 0;">
                  <%= link_to "Visiter", @experience.url, target:"_blank", class: "btn btn-primary" %>
                </div>
              <% end %>
              <div style="position: absolute; top: -45px; max-width: 75%;">
                <%= @experience.address %>
              </div>
              <div>
                <%= cl_image_tag @experience.user.avatar.path, crop: :fill, size: "30x30", class: "avatar", gravity: :face %>
                <span class="author-name"><%= "#{@experience.user.first_name} #{@experience.user.last_name[0].upcase}." %></span>
              </div>
              <div class="interaction-buttons">
                <% if user_signed_in? %>
                  <%= render 'wishlists/heart', wished: @wished, wishlist: @wishlist, experience: @experience %>
                <% end %>
                <a class="icon-controlled-access" style="margin-left: 5px;" data-toggle="modal" data-target="#sendExperience">
                  <%= icon('envelope-o') %>
                </a>
                <%= render "shared/facebook_share", url: experience_url(@experience), title: @experience.title, description: @experience.description, photo: cl_image_path(@experience.photos[0].path) %>

                <div class="modal fade" id="sendExperience" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">À qui voulez-vous partager ce coup de coeur?</h4>
                      </div>
                      <div class="modal-body input">
                        <%= simple_form_for :send_experience, url: experience_send_path(@experience) do |f| %>
                          <%= f.input :recipient, label: "Adresse e-mail", placeholder: "jean.martin@gmail.com" %>
                          <hr>
                          <%= f.submit "Partager", class: "btn btn-succes btn-block" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>


              </div>
            </div>
          </div>
        </div>
        <div class="reviews col-md-10 col-offset-1">
          <% if user_signed_in? && policy(@rating).new? %>
            <%= render "shared/review_form", locals: { parent: @experience, review: @rating } %>
          <% end %>
          <% @experience.ratings.each do |rating| %>
            <%= render "shared/review", locals: { review: rating } %>
          <% end %>
        </div>
      </div>
      <div class="block-right col-md-6">
        <div class="row">
          <div class="pictures col-md-12">
            <%= cl_image_tag @experience.photos[0].path, class: "main-picture", crop: :fill %>
            <div class="sub-pictures">
              <% if @experience.photos.length > 1 %>
                <% @experience.photos.each do |photo| %>
                  <%= cl_image_tag photo.path, crop: :lfill, class: "sub-picture" %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="map-wrapper">
              <%= render "shared/map" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :after_js do %>
<script>
  $(document).ready(function(){
    $('.pictures img').hover(function(e){
      save = $(".main-picture")[0].src
      $(".main-picture")[0].src = $(this)[0].src;
    }, function(e){
      $(".main-picture")[0].src = save;
    });
    $('.pictures img').click(function(e){
      save = $(".main-picture")[0].src
    });
  });
</script>
<% end %>