config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#landing_page'

  post "/" => 'pages#save_email'

  get "contact" => "pages#contact"
  post "contact" => "pages#contact_mail"

  get "cgu" => "pages#cgu"

  mount Attachinary::Engine => "/attachinary"

  resources :experiences do
    post "send_experience" => "experiences#send_experience", as: 'send'
    resources :ratings, only: [:create]
    resources :wishlists, only: [:create]
  end

  post "gps_coordinates" => "images#get_gps"

  resources :roadmaps do
    get "send_roadmap" => "roadmaps#send_roadmap", as: 'send'
    resources :experiences do
      resources :activities, only: [:create]
    end
  end

  resources :roadmaps
  resources :activities, only: [:update, :destroy] do
    post "up" => "activities#up"
    post "down" => "activities#down"
  end

  get "my_experiences" => "experiences#my_experiences"

  resources :wishlists, only: [:index, :destroy]
  resources :ratings, only: [:destroy]
 end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :experience

  validates :user_id, uniqueness: { scope: :experience_id }
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
# Wishlists are a collection of Experiences specific to each user that they can then browse.
  before_action :getParams, only: [:create, :destroy]

  def index
    wishlists = policy_scope(Wishlist)
    @groups = wishlists.group_by { |w| w.experience.country }
    @groups = @groups.each { |country, g| @groups[country] = g.group_by { |w| w.experience.city } }
  end

  def create
    @wishlist = current_user.wishlists.new()
    @wishlist.experience = Experience.find(params[:experience_id])
    authorize(@wishlist)
    @experience = @wishlist.experience
    if @wishlist.save
      @wished = true
      respond_to do |format|
        format.html { redirect_to experience_path(@wishlist.experience) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'experiences/show' }
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    authorize(@wishlist)
    @wishlist.destroy
    @wished = false
    @experience = @wishlist.experience
    respond_to do |format|
      format.html { redirect_to @experience }
      format.js
    end

  end

  private

  def wishlist_params
    params[:wishlist][:experience_id] = params[:experience_id] if params[:wishlist]
    params.require(:wishlist).permit(:user_id, :experience_id)
  end

  def getParams
    @delete_after = (params[:deleteAfter] == "true")
    @notext = (params[:notext] == "true")
  end
end

app/views/wishlists/_heart.html.erb
<div class="wishlist-btn" id="wishlist_<%= experience.id %>">
  <% notext ||= false %>
  <% delete_after ||= false %>
  <% unless notext %>
    <span class="bookmark">Bookmark </span>
  <% end %>

  <% if wished %>

    <%= link_to '#', id:"wishlist-#{experience.id}-link" do %>
      <i class="fa fa-heart"></i>
    <% end %>

  <% else %>

    <%= link_to '#', id:"wishlist-#{experience.id}-link" do %>
      <i class="fa fa-heart-o"></i>
    <% end %>

  <% end %>
</div>

<% content_for :after_js do %>
  <script>
    $(document).ready(function(){
      $("#wishlist-<%= experience.id %>-link").click(function(e){
        e.preventDefault();
        <% if wished %>
          $.ajax({
            method: "delete",
            url: "<%= j wishlist_path(wishlist) %>.js",
            data: {
              notext: <%= notext %>,
              deleteAfter: <%= delete_after %>
            }
          });
        <% else %>
          $.ajax({
            method: "post",
            url: "<%= j experience_wishlists_path(experience) %>.js",
            data: {
              notext: <%= notext %>,
              deleteAfter: <%= delete_after %>
            }
          });
        <% end %>
      })
    });
  </script>
<% end %>

app/views/wishlists/create.js.erb
<% if @wishlist.errors.any? %>
  // Render new wishlist form with errors
  raise
<% else %>
  $('#wishlist_<%= @experience.id %>').replaceWith("<%= j render 'wishlists/heart', wished: @wished, wishlist: @wishlist, experience: @experience, notext: @notext %>");
  $('#wishlist i').addClass('heart-beating');
<% end %>

$(document).ready(function(){
  $("#wishlist-<%= @experience.id %>-link").click(function(e){
    e.preventDefault();
    <% if @wished %>
      $.ajax({
        method: "delete",
        url: "<%= j wishlist_path(@wishlist) %>.js",
        data: {
          notext: <%= @notext %>
        }
      });
    <% else %>
      $.ajax({
        method: "post",
        url: "<%= j experience_wishlists_path(@experience) %>.js",
        data: {
          notext: <%= @notext %>
        }
      });
    <% end %>
  })
});

app/views/wishlists/destroy.js.erb
<% if @delete_after %>
   $('#wishlist_<%= @experience.id %>').parent().parent().parent().remove();
<% else %>
  $('#wishlist_<%= @experience.id %>').replaceWith("<%= j render 'wishlists/heart', wished: @wished, wishlist: @wishlist, experience: @experience, notext: @notext %>");
  $('#wishlist_<%= @experience.id %> i').addClass('heart-beating');
<% end %>
$(document).ready(function(){
  $("#wishlist-<%= @experience.id %>-link").click(function(e){
    e.preventDefault();
    <% if @wished %>
      $.ajax({
        method: "delete",
        url: "<%= j wishlist_path(@wishlist) %>.js",
        data: {
          notext: <%= @notext %>
        }
      });
    <% else %>
      $.ajax({
        method: "post",
        url: "<%= j experience_wishlists_path(@experience) %>.js",
        data: {
          notext: <%= @notext %>
        }
      });
    <% end %>
  })
});

app/views/wishlists/index.html.erb
<div class="container search-form">
  <div class="search-center">
    <h2>Mes favoris :</h2>
  </div>
</div>

<div class="block-contain">
  <div class="container">
    <% @groups.each do |country, content| %>
      <div class="row">
        <h3><%= country %></h3>
        <div class="container" style="padding-left:50px;">
          <% content.sort_by { |_,w| -w.length }.each do |city, wishlists| %>
            <div class="row">
              <h3><%= city %></h3>
              <% wishlists.each do |wishlist| %>
                <div class="col-xs-12 col-sm-4">
                  <%= render "shared/card", experience: wishlist.experience, deletable: true %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>